### ISSUE TITLE
不准备把app的源码分享出来吗

### ISSUE THREAD

**Issue by jiang111** [leon0516/jw-wxit-helper#1]
我在想，学校有没有要收购你app的计划

**Comment by leon0516** [comment]
我找找。。。。有可能找不到了。。。。

**Comment by leon0516** [comment]
另外，学校的接口也不能用了。这个软件许多功能也用不了了。。。

**Comment by leon0516** [comment]
找到了，已开源 [leon0516/WXIThelper](https://github.com/leon0516/WXIThelper)

**Comment by jiang111** [comment]
建议你通过老师找学校商量一下，说不定学校可能给你点操作数据库的权限
